// components/Footer.vue
<template>
    <footer class="relative border-t border-zinc-900">

        <div class="absolute inset-x-0 flex items-center justify-center -top-3">
            <div class="relative flex justify-center h-10 w-14">
                <div class="absolute w-full h-full inset-0 -top-[2px] blur-[6px] bg-black rounded-full">
                </div>
                <img src="/img/logo.svg" class="relative w-6 h-6">
            </div>
        </div>

        <div class="max-w-screen-lg mx-auto py-8">

            <div class="sm:relative flex flex-col items-center gap-3 lg:flex-row sm:justify-between">


                <span class="text-xs text-gray-300">© BSS OSF - All Rights Reserved.</span>


                <div class="text-sm font-medium text-gray-300 px-4">
                    <ul class="gap-6 flex flex-wrap justify-center">
                        <li>
                            <NuxtLink to="/" class="hover:text-blue-600">
                                HOME
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/download" class="hover:text-blue-600">
                                DOWNLOAD
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/about" class="hover:text-blue-600">
                                ABOUT
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/privacy" class="hover:text-blue-600">
                                PRIVACY
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/team" class="hover:text-blue-600">
                                TEAM
                            </NuxtLink>
                        </li>
                    </ul>
                </div>


                <div class="flex flex-wrap gap-6">

                    <a href="https://github.com/parchlinux" target="_blank">
                        <Icon name="uil:github" class="w-5 h-5 hover:scale-110 transition"/>
                    </a>

                    <a href="https://twitter.com/bssfoss" target="_blank">
                        <Icon name="uil:twitter" class="w-5 h-5 hover:scale-110 transition"/>
                    </a>

                    <a href="https://discord.gg/9RW5cRByAM" target="_blank">
                        <Icon name="ic:baseline-discord" class="w-5 h-5 hover:scale-110 transition"/>
                    </a>

                </div>

            </div>



    </div>
</footer></template>
<script>
export default {

}
</script>

// src/components/Footer.jsx
import { FaGithub, FaDiscord, FaInstagram, FaLinkedinIn, FaTwitter, FaDev, FaTelegramPlane, FaGitlab } from 'react-icons/fa'



const Footer = () => {
  return (

    <footer className="p-4 shadow-[0_0_70px_theme('colors.sky.950')]">

      <div className="flex flex-col items-center justify-center sm:flex-row sm:justify-between">
        <span className="text-sm text-center sm:text-left leading-loose	 font-medium">© 2023 <a target="_blank"
          href="https://bssinc.ir" className="underline hover:text-sky-500 transition">BSS OSF</a>. All Rights Reserved. <br/>

            <span className="text-xs">
              Made with ❤️ By <a target="_blank" href="https://pycloud.space" className="underline hover:text-sky-500 transition">AFz.</a>
            </span>
        </span>


        <div className="flex mt-4 space-x-6 sm:justify-center sm:mt-0">


          <a target="_blank" href="https://github.com/parchlinux" className="hover:bg-zinc-900 p-1 rounded-md">
            <FaGithub className='w-6 h-6'/>
          </a>

        </div>
      </div>
    </footer>

  )
}

export default Footer
