// components/Navbar.vue
<template>
    <nav class="p-4 w-full flex justify-between items-center z-50">

        <div class="flex items-center gap-1">
            <!-- <h1 class="text-xl font-bold">Parch Linux</h1> -->
            <img src="/img/logo.svg" alt="Logo" class="w-10 h-10">
        </div>

        <div class="lg:hidden">
            <Icon name="ic:round-menu" @click="menuToggle = !menuToggle"
                class="w-9 h-9 hover:bg-zinc-900 rounded-lg p-1.5 transition" />
        </div>

        <div class="hidden lg:block">
            <ul class="gap-6 flex flex-wrap">
                <li>
                    <NuxtLink to="/" class="hover:text-blue-600">
                        Home
                    </NuxtLink>
                </li>
                <li>
                    <NuxtLink to="/download" class="hover:text-blue-600">
                        Download
                    </NuxtLink>
                </li>
                <li>
                    <a href="https://parchlinux.ir/blog/" class="hover:text-blue-600">
                        Blog
                    </a>
                </li>
                <li>
                    <a href="https://parchlinux.ir/parchwiki/" class="hover:text-blue-600">
                        Wiki
                    </a>
                </li>
                <li>
                    <NuxtLink to="/about" class="hover:text-blue-600">
                        About
                    </NuxtLink>
                </li>
            </ul>
        </div>


        <div class="hidden lg:flex flex-wrap gap-6">

            <a href="https://github.com/parchlinux" target="_blank">
                <Icon name="uil:github" class="w-5 h-5 hover:scale-110 transition" />
            </a>

            <a href="https://twitter.com/bssfoss" target="_blank">
                <Icon name="uil:twitter" class="w-5 h-5 hover:scale-110 transition" />
            </a>

            <a href="https://discord.gg/9RW5cRByAM" target="_blank">
                <Icon name="ic:baseline-discord" class="w-5 h-5 hover:scale-110 transition" />
            </a>

        </div>
    </nav>
</template>
<script setup>

let menuToggle = useMenuToggle()

</script>

// src/components/Navbar.jsx
import { useState } from 'react'
import { NavLink } from 'react-router-dom'

import { HiBars3BottomRight, HiXMark, HiOutlineNewspaper, HiOutlinePhone, HiOutlineExclamationCircle } from 'react-icons/hi2'
import { HiDownload, HiOutlineBookOpen } from 'react-icons/hi'


const Navbar = () => {

  const [toggleMenu, setToggleMenu] = useState(false);

  return (
    <nav className="w-full h-14 p-10 lg:px-16 flex justify-between items-center">

      <NavLink to={'/'}>
        <div className='border-2 rounded-md border-sky-500 p-1 px-2'>
          <h1 className='font-semibold text-2xl text-sky-500'>PARCH</h1>
        </div>
      </NavLink>

      <div>
        <ul className='text-sm font-medium hidden sm:flex justify-end items-center space-x-4'>
          <li>
            <NavLink className='hover:text-sky-500 transition' to={'/get-parch'}>
              GET PARCH
            </NavLink>
          </li>
          <li>
            <a target='_blank' href='https://parchlinux.ir/blog/' className='hover:text-sky-500 transition'>
              BLOG
            </a>
          </li>

          <li>
            <NavLink className='hover:text-sky-500 transition' to={'/about'}>
              ABOUT
            </NavLink>
          </li>

          <li>
            <a target="_blank" href='https://parchlinux.ir/parchwiki/' className='hover:text-sky-500 transition'>
              WIKI
            </a>
          </li>
        </ul>
      </div>


      <div className='sm:hidden flex flex-1 justify-end items-center'>
        <button onClick={() => setToggleMenu(!toggleMenu)} className='hover:bg-zinc-800 p-2 rounded-full'>
          {!toggleMenu ?
            <HiBars3BottomRight className='w-7 h-7' /> :

            <HiXMark className='w-7 h-7' />
          }
        </button>


        <div className={`${toggleMenu ? 'flex' : 'hidden'} p-6 bg-zinc-900 absolute top-16 right-4 px-2 py-4 min-w-[140px] rounded`}>
          <ul className="space-y-2 w-[180px] text-xs font-medium">
            <li>
              <NavLink to={'/get-parch'} onClick={() => setToggleMenu(setToggleMenu(false))} className="flex items-center p-2 text-gray-50 hover:bg-zinc-800 rounded-lg ">
                <HiDownload className="flex-shrink-0 w-6 h-6  transition duration-75 text-gray-400" />
                <span className="flex-1 ml-3 whitespace-nowrap">GET PARCH</span>

              </NavLink>
            </li>

            <li>
              <NavLink to={'/blog'} onClick={() => setToggleMenu(setToggleMenu(false))} className="flex items-center p-2 text-gray-50 hover:bg-zinc-800 rounded-lg ">
                <HiOutlineNewspaper className="flex-shrink-0 w-6 h-6  transition duration-75 text-gray-400" />
                <span className="flex-1 ml-3 whitespace-nowrap">BLOG</span>

              </NavLink>
            </li>

            <li>
              <NavLink to={'/about'} onClick={() => setToggleMenu(setToggleMenu(false))} className="flex items-center p-2 text-gray-50 hover:bg-zinc-800 rounded-lg ">
                <HiOutlineExclamationCircle className="flex-shrink-0 w-6 h-6  transition duration-75 text-gray-400" />
                <span className="flex-1 ml-3 whitespace-nowrap">ABOUT</span>

              </NavLink>
            </li>

            <li>
              <NavLink to={'/wiki'} onClick={() => setToggleMenu(setToggleMenu(false))} className="flex items-center p-2 text-gray-50 hover:bg-zinc-800 rounded-lg ">
                <HiOutlineBookOpen className="flex-shrink-0 w-6 h-6  transition duration-75 text-gray-400" />
                <span className="flex-1 ml-3 whitespace-nowrap">WIKI</span>

              </NavLink>
            </li>

          </ul>
        </div>
      </div>

    </nav>
  )
}
export default Navbar
