// src/components/about/Privacy.jsx
const Privacy = () => {
    return (
        <section className="max-w-[860px] flex items-center justify-center flex-col mx-auto p-6 min-h-screen">
            <div className="flex flex-col justify-center px-4 mb-20 mt-10">

                <h1 className="text-3xl sm:text-[45px] font-bold" style={{ textWrap: 'balance', }}>Privacy Policy</h1>

                <div className='mt-6'>
                    <p className="font-normal text-[15px] leading-6">

                        Last updated: August 7, 2023 <br /> <br />

                        Parch Linux ("us", "we", or "our") operates the <a href="https://www.parchlinux.ir" className='text-sky-500'>parchlinux.ir</a> website and related services on a non-profit basis. Parch Linux releases and distributions may originate from the core Parch Linux team or the broader Parch Linux community (the "Service"). <br /><br />

                        This page informs you of our policies regarding the collection, use and disclosure of information when you use our Service. <br /><br />

                        <strong>Information Collection and Use</strong> <br /><br />

                        As Parch Linux is a non-profit, open source Linux distribution, neither the core team nor the community collect any Personal Information or non-Personal Information such as cookies from users browsing our website or downloading/using Parch Linux. <br /><br />

                        The Parch Linux website does not use cookies or any other means to collect data from visitors. <br /><br />

                        Some tools included in Parch Linux may be developed by third parties outside of the Parch Linux project. Those tools are subject to their own privacy policies. Parch Linux is not responsible or liable for the content, privacy policies or practices of third party tools/apps not developed by the Parch Linux team or community. <br /><br />

                        The Parch Linux team is not responsible for any third party repositories that are not approved or endorsed by Parch Linux. <br /><br />

                        Most Parch Linux components are licensed under the GPL-3 license. Users should refer to the applicable license terms for each component for details. <br /><br />

                        The only telemetry data collected by Parch Linux relates to desktop environments like KDE Plasma or GNOME, to provide statistics to those developers. This is controlled by the environments' privacy settings, not Parch Linux. <br /><br />

                        Changes To This Privacy Policy

                        We may update this Privacy Policy periodically. You should review this page to check for updates. Continued use of the Service after any changes constitutes acceptance of the revised Privacy Policy.

                        Contact Us

                        If you have any questions about this Privacy Policy, please contact us or the Parch Linux community.
                    </p>
                </div>

            </div>

        </section>

    )
}

export default Privacy

// pages/privacy.vue
<template>
    <div class="max-w-[860px] flex items-center flex-col mx-auto p-6 min-h-screen">
        <div class="flex flex-col justify-center px-4 mb-20 mt-10">

            <h1 class="text-3xl sm:text-[45px] font-bold">Privacy Policy</h1>

            <div class='mt-6'>
                <p class="font-normal text-[15px] leading-6">

                    Last updated: August 7, 2023 <br /> <br />

                    Parch Linux ("us", "we", or "our") operates the <a href="https://www.parchlinux.ir"
                        class='text-sky-500'>parchlinux.ir</a> website and related services on a non-profit basis. Parch
                    Linux releases and distributions may originate from the core Parch Linux team or the broader Parch Linux
                    community (the "Service"). <br /><br />

                    This page informs you of our policies regarding the collection, use and disclosure of information when
                    you use our Service. <br /><br />

                    <strong>Information Collection and Use</strong> <br /><br />

                    As Parch Linux is a non-profit, open source Linux distribution, neither the core team nor the community
                    collect any Personal Information or non-Personal Information such as cookies from users browsing our
                    website or downloading/using Parch Linux. <br /><br />

                    The Parch Linux website does not use cookies or any other means to collect data from visitors.
                    <br /><br />

                    Some tools included in Parch Linux may be developed by third parties outside of the Parch Linux project.
                    Those tools are subject to their own privacy policies. Parch Linux is not responsible or liable for the
                    content, privacy policies or practices of third party tools/apps not developed by the Parch Linux team
                    or community. <br /><br />

                    The Parch Linux team is not responsible for any third party repositories that are not approved or
                    endorsed by Parch Linux. <br /><br />

                    Most Parch Linux components are licensed under the GPL-3 license. Users should refer to the applicable
                    license terms for each component for details. <br /><br />

                    The only telemetry data collected by Parch Linux relates to desktop environments like KDE Plasma or
                    GNOME, to provide statistics to those developers. This is controlled by the environments' privacy
                    settings, not Parch Linux. <br /><br />

                Changes To This Privacy Policy

                We may update this Privacy Policy periodically. You should review this page to check for updates.
                Continued use of the Service after any changes constitutes acceptance of the revised Privacy Policy.

                Contact Us

                If you have any questions about this Privacy Policy, please contact us or the Parch Linux community.
            </p>
        </div>

    </div>
</div></template>
